# Generated by Django 6.0.5 on 2026-05-23 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employe_managers_alter_employe_role'),
        ('poste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('FREELANCE', 'Prestation Freelance')], default='CDI', max_length=15, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salaire de base')),
                ('statut', models.CharField(choices=[('ACTIF', 'En cours'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='employees.employe', verbose_name='Employé')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='poste.poste', verbose_name='Poste')),
            ],
        ),
    ]
