# Generated by Django 6.0.5 on 2026-05-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employe_managers_alter_employe_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_rapport', models.CharField(choices=[('EFFECTIFS', 'Rapport effectifs'), ('PRESENCES', 'Rapport présences'), ('ABSENCES', 'Rapport absences'), ('CONGES', 'Rapport congés'), ('JUSTIFICATIONS', 'Rapport justifications'), ('SALAIRES', 'Rapport salaires'), ('MENSUEL', 'Rapport mensuel complet')], max_length=30, verbose_name='Type de rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Période début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Période fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données du rapport')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to='employees.employe', verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'ordering': ['-date_creation'],
            },
        ),
    ]
