# Generated by Django 6.0.5 on 2026-06-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Rapport', 'verbose_name_plural': 'Rapports'},
        ),
    ]
