# Generated by Django 6.0.5 on 2026-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employe_managers_alter_employe_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150, verbose_name='Intitulé du poste')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau_hierarchie', models.CharField(choices=[('JUNIOR', 'Junior'), ('CONFIRME', 'Confirmé'), ('SENIOR', 'Senior'), ('MANAGER', 'Manager'), ('DIRECTION', 'Direction')], default='JUNIOR', max_length=20, verbose_name='Niveau')),
                ('salaire_min', models.FloatField(default=0, verbose_name='Salaire minimum')),
                ('salaire_max', models.FloatField(default=0, verbose_name='Salaire maximum')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Poste actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employes', models.ManyToManyField(blank=True, related_name='postes', to='employees.employe', verbose_name='Employés')),
            ],
            options={
                'verbose_name': 'Poste',
                'ordering': ['intitule'],
            },
        ),
    ]
