# Generated by Django 6.0.5 on 2026-05-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conge',
        ),
    ]
