# Generated by Django 6.0.5 on 2026-06-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de validateur'),
        ),
        migrations.AddField(
            model_name='conge',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conge',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du validateur'),
        ),
    ]
