# Generated by Django 6.0.5 on 2026-05-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employe_managers_alter_employe_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('CONGE_SOUMIS', 'Congé soumis'), ('CONGE_APPROUVE', 'Congé approuvé'), ('CONGE_REFUSE', 'Congé refusé'), ('JUSTIF_SOUMISE', 'Justification soumise'), ('JUSTIF_VALIDEE', 'Justification validée'), ('JUSTIF_REJETEE', 'Justification rejetée'), ('ANNIVERSAIRE', 'Anniversaire'), ('RAPPEL', 'Rappel administratif'), ('SYSTEME', 'Message système')], max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='Lien (optionnel)')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employe', verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
