# Generated by Django 6.0.5 on 2026-06-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='destinataire',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de destinataire'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du destinataire'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('CONGE_SOUMISE', 'Congé soumis'), ('CONGE_APPROUVE', 'Congé approuvé'), ('CONGE_REFUSE', 'Congé refusé'), ('JUSTIF_SOUMISE', 'Justification soumise'), ('JUSTIF_VALIDEE', 'Justification validée'), ('JUSTIF_REJETEE', 'Justification rejetée'), ('ANNIVERSAIRE', 'Anniversaire'), ('RAPPEL', 'Rappel administratif'), ('SYSTEME', 'Message système')], max_length=30, verbose_name='Type'),
        ),
    ]
