# Generated by Django 6.0.5 on 2026-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_type_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('CONGE_SOUMIS', 'Congé soumis'), ('CONGE_APPROUVE', 'Congé approuvé'), ('CONGE_REFUSE', 'Congé refusé'), ('JUSTIF_SOUMISE', 'Justification soumise'), ('JUSTIF_VALIDEE', 'Justification validée'), ('JUSTIF_REJETEE', 'Justification rejetée'), ('JUSTIF_SUPPRIMEE', 'Justification supprimée'), ('ANNIVERSAIRE', 'Anniversaire'), ('RAPPEL', 'Rappel administratif'), ('SYSTEME', 'Message système'), ('CONTRAT_EXPIRE_SOON', 'Contrat expirant bientôt'), ('CONTRAT_EXPIRE', 'Contrat expiré'), ('CONTRAT_CREE', 'Nouveau contrat créé'), ('CONTRAT_CLOTURE', 'Contrat clôturé')], max_length=30, verbose_name='Type'),
        ),
    ]
