# Generated by Django 6.0.5 on 2026-05-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrateur',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='role',
            field=models.CharField(blank=True, choices=[('EMPLOYE', 'Employé'), ('RH', 'Gestionnaire RH'), ('ADMIN', 'Administrateur')], max_length=20),
        ),
    ]
