# Generated by Django 6.0.5 on 2026-05-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0002_alter_administrateur_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={'verbose_name': 'Administrateur'},
        ),
    ]
