# Generated by Django 6.0.5 on 2026-05-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_alter_administrateur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={'verbose_name': 'RH'},
        ),
    ]
