# Generated by Django 6.0.5 on 2026-05-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0004_alter_administrateur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={'verbose_name': 'Administrateur'},
        ),
    ]
