# Generated by Django 6.0.5 on 2026-05-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0002_alter_employe_options_employe_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', related_query_name='%(class)s', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', related_query_name='%(class)s', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
