# Generated by Django 6.0.5 on 2026-05-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employe_managers_alter_employe_role'),
        ('presences', '0002_delete_conge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_justif', models.CharField(choices=[('RETARD', 'Retard'), ('ABSENCE', 'Absence')], max_length=20, verbose_name='Type')),
                ('motif', models.TextField(verbose_name='Motif de la justification')),
                ('document', models.FileField(blank=True, null=True, upload_to='justifications/', verbose_name='Document justificatif (optionnel)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('commentaire_rh', models.TextField(blank=True, verbose_name='Commentaire RH')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='employees.employe', verbose_name='Employé')),
                ('presence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='presences.presence', verbose_name='Présence concernée')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_validees', to='employees.employe', verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Justification',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
