# Generated by Django 6.0.5 on 2026-06-04 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('justification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justification',
            name='valide_par',
        ),
        migrations.AddField(
            model_name='justification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de validateur'),
        ),
        migrations.AddField(
            model_name='justification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du validateur'),
        ),
    ]
