# Generated by Django 6.0.5 on 2026-06-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justification', '0002_remove_justification_valide_par_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='document',
            field=models.FileField(blank=True, help_text='PDF, JPG, PNG, DOC (max 5 Mo)', null=True, upload_to='justifications/', verbose_name='Document justificatif (optionnel)'),
        ),
    ]
